# Generated by Django 3.0.6 on 2020-05-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hitchspot',
            fields=[
                ('spot_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
                ('avg_hitchability', models.FloatField()),
                ('avg_waiting_time', models.FloatField()),
                ('creation_date', models.DateField()),
                ('update_date', models.DateField()),
                ('country_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
