# Generated by Django 3.0.6 on 2020-06-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitchify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='src_file',
            field=models.ImageField(default='default.jpg', upload_to='photos/'),
        ),
    ]
