# Generated by Django 3.0.6 on 2020-06-08 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitchify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='core_user',
            new_name='user',
        ),
    ]
