# Generated by Django 3.0.6 on 2020-06-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitchify', '0002_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'managed': False},
        ),
    ]
