# Generated by Django 3.0.6 on 2020-06-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitchify', '0002_auto_20200608_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
