# Generated by Django 3.0.6 on 2020-06-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitchify', '0002_auto_20200612_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
