# Generated by Django 3.0.6 on 2020-05-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitchify', '0003_auto_20200506_1945'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hitchspot',
            table='hitchspot',
        ),
    ]
