# Generated by Django 3.0.6 on 2020-06-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitchify', '0003_auto_20200613_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='base_user',
            field=models.IntegerField(default=-1),
        ),
    ]
