# Generated by Django 3.0.6 on 2020-06-04 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitchify', '0003_auto_20200605_0103'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
    ]
