# Generated by Django 3.0.6 on 2020-06-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitchify', '0003_remove_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='src_file',
            field=models.ImageField(default='default.jpg', upload_to='photos/'),
        ),
    ]
