# Generated by Django 3.0.6 on 2020-06-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitchify', '0003_auto_20200608_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user',
        ),
    ]
