# Generated by Django 3.0.6 on 2020-06-08 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hitchify', '0004_remove_myuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitchspot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
