# Generated by Django 3.0.6 on 2020-06-13 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hitchify', '0004_myuser_base_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='base_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
