# Generated by Django 3.0.6 on 2020-06-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitchify', '0005_auto_20200613_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
