# Generated by Django 3.0.6 on 2020-06-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitchify', '0007_auto_20200615_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.TextField(default='https://dapp.dblog.org/img/default.jpg'),
        ),
    ]
